Repository frouriojs/frourio.com, pull requests merged in 2021-01, with the labels that each got.

#18 #15 OneTS.svg, architecture.svg に非ASCII文字が含まれていた
  static/img/OneTS.svg
  static/img/architecture.svg
Labels: bug

#20 レイアウト変更・速度グラフを下に移動
  src/pages/index.js
Labels: design / style

#22 最新Masterを取り込み
  .github/workflows/documentation.yml
  docs/authentication.mdx
  docs/dependency-injection.md
  docs/hooks/additional-request.mdx
  docs/installation/cui.mdx
  docs/installation/gui.mdx
  docs/introduction.md
  docs/pathpida/with-nextjs.mdx
  docs/pathpida/with-nuxtjs.mdx
  docusaurus.config.js
  package.json
  sidebars.js
  src/components/BrowserWindow/index.tsx
  src/css/custom.css
  src/pages/index.tsx
  static/img/OneTS.svg
  static/img/TwoTS.svg
  static/img/architecture.svg
  tsconfig.json
  yarn.lock
Labels: design / style

#23 code block設置
  src/pages/CodeBlocks.tsx
  src/pages/HowtoSetup.tsx
  src/pages/index.tsx
  src/pages/styles.module.css
  static/img/communication.jpg
  static/img/keyvisual.jpg
  static/img/speed.png
Labels: design / style

#25 add changelog page
  docusaurus.config.js
  package.json
  src/css/custom.css
  src/libs/markdown.ts
  src/pages/changelog.module.css
  src/pages/changelog.tsx
  yarn.lock
Labels: documentation

#28 #26 add fallback to Japanese font
  src/css/custom.css
Labels: design / style

#30 fix: typo Tarminal -> Terminal
  docs/installation/cui.mdx
Labels: documentation
